### PR TITLE
Update for .NET Core 2.1.300

### PR DESCRIPTION
**Pull request by qayshp**
README
* Change `dotnet install tool` -> `dotnet tool install`
* Update preview download link to RC1

csproj
* Tick version to `1.0.1`
* Use `netcoreapp2.1`

### CODE REVIEW

**Comment by qayshp** [comment]
After these changes I was able to use your wonderful tool!

```
git clean -fxd; git clean -fXd
dotnet pack --output /tmp/casa
dotnet tool install -g dotnet-addcasa --source-feed /tmp/casa --version 1.0.1
cd <some other project>
dotnet addcasa
```

**Comment by cmendible** [comment]
wow! sorry somehow I missed your PR. You mind updating it for the latest release: 2.1.300?

Thanks!

**Comment by cmendible** [comment]
Thanks @qayshp for contributing!!!

**Comment by qayshp** [comment]
Sorry I didn't get around to updating it for the release, but thanks for doing that and merging!

**Pull request merged**
